### ISSUE TITLE
Loading request Does not handle rotation properly

### ISSUE THREAD

**Issue by ChamzasKonstantinos** [KavrakiLab/robowflex#53]
When I create a planning request in gazebo and store it through robowflex when I load it I think the orientation of the goal is applied two times. I found out that if I change the orientation constraints in the dumped yaml file to [[0,0,0,1]]

 it is visualized and used correctly. 
```
goal_constraints:
  - orientation_constraints:
      - header:
          frame_id: base_link
IF I CHANGE THIS--->orientation: [0.002169335706511942, 0.003783045166177664, -0.1093575153225559, 0.9939929156660725]**
        link_name: gripper_link
        absolute_x_axis_tolerance: 0.001
        absolute_y_axis_tolerance: 0.001
        absolute_z_axis_tolerance: 0.001
    position_constraints:
      - header:
          frame_id: base_link
        link_name: gripper_link
        constraint_region:
          primitives:
            - type: sphere
              dimensions: [0.001]
          primitive_poses:
            - position: [0.7372066420855821, -0.1190740568951352, 1.00846964894857]
              orientation: [0.002169335706511949, 0.003783045166177633, -0.1093575153225559, 0.9939929156660725]
```
First picture is the wrong orientation last picture is the correct orientation
![bad_goal](https://user-images.githubusercontent.com/5930462/68436800-a8f28b80-0184-11ea-9ca5-e399f96ff23f.png)
![good_goal](https://user-images.githubusercontent.com/5930462/68436805-ab54e580-0184-11ea-9026-fb4d3f42d688.png)
